<div class="main_pic"><img src="/img/Maison-logo.jpg"></div>
<div class="main_opt">
<h1>Module Clients</h1>
<a class="button big" href="<?php echo $this->url(array('controller'=>'clients', 'action'=>'newresa')); ?>">Ajouter une nouvelle réservation</a>
<a class="button big" href="<?php echo $this->url(array('controller'=>'clients', 'action'=>'liste')); ?>">Liste des réservations</a>
<a class="button big" href="<?php echo $this->url(array('controller'=>'clients', 'action'=>'listeclients')); ?>">Liste des clients</a>
<a class="button big" href="<?php echo $this->url(array('controller'=>'clients', 'action'=>'stats')); ?>">Statistiques</a>
</div>