<script src="../../../../Scripts/swfobject_modified.js" type="text/javascript"></script>
<div class="main_pic"><img src="/img/Maison-logo.jpg"></div>
<div class="main_opt">
<h1>Videos d'aide</h1>
<p><a href="/video/depenses.swf">Comment ajouter une nouvelle dépense ?</a></p>
<p><a href="/video/reservation.swf">Comment ajouter une nouvelle réservation ?</a></p>
<p><a href="/video/Stats.swf">Comment utiliser les statistiques ?</a></p>
<p><a href="/video/livrecomptes.swf">Comment consulter le livre de comptes ?</a></p>
<p><a href="/video/rapports.swf">Comment lire les autres rapports financiers ?</a></p>
<p><a href="/video/admin.swf">A quoi sert l'onglet "Administration" ?</a></p>
</div>
<script type="text/javascript">
swfobject.registerObject("FlashID");
</script>
