<div class="main_pic"><img src="/img/Maison-logo.jpg"></div>
<div class="main_opt">
<h1>Nouvelle Dépense</h1>
<a class="button" href="<?php echo $this->url(array('controller'=>'operation', 'action'=>'newentretien')); ?>">Nouvelle dépense d'entretien d'appartement</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'operation', 'action'=>'newofficeexp')); ?>">Nouvelle dépense d'entretien de bureau</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'operation', 'action'=>'newfraisdep')); ?>">Frais de déplacement</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'operation', 'action'=>'newofficestuff')); ?>">Achat de fournitures de bureau</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'operation', 'action'=>'newproffee')); ?>">Honoraires professionels</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'operation', 'action'=>'newpub')); ?>">Publicité, Cotisations et abonnements divers</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'operation', 'action'=>'newinvit')); ?>">Invitations</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'operation', 'action'=>'newfinancialfee')); ?>">Frais financiers</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'operation', 'action'=>'newequip')); ?>">Achat d'équipements</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'operation', 'action'=>'newcustom')); ?>">Nouvelle opération spéciale</a>
</div>