<div class="main_pic"><img src="/img/Maison-logo.jpg"></div>
<div class="main_opt">
<h1>Choisissez un type de rapport comptable :</h1>
<a class="button big" href="<?php echo $this->url(array('controller'=>'rapport', 'action'=>'livres')); ?>">Livre de compte</a>
<a class="button big" href="<?php echo $this->url(array('controller'=>'rapport', 'action'=>'resultats')); ?>">Resultats</a>
<a class="button big" href="<?php echo $this->url(array('controller'=>'rapport', 'action'=>'bilan')); ?>">Bilan</a>
<a class="button big" href="<?php echo $this->url(array('controller'=>'rapport', 'action'=>'projection')); ?>">Projection de revenus</a>
</div>
